# Generated by Django 5.0 on 2025-05-21 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0001_initial'),
        ('proyectos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='convenios.convenio'),
        ),
    ]
