# Generated by Django 5.0 on 2025-05-21 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0001_initial'),
        ('proyectos', '0003_proyecto_convenio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='convenio',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='convenios.empresa'),
        ),
    ]
